### ISSUE TITLE
V0.0.1 Questions, Updates and issues

### ISSUE THREAD

**Issue by fallengravity** [Asymetrex/desktop-app#2]
You might not have implemented it yet but the application opens extremely small, I imagine we could modify it to launch in full screen by default and then save the users size (I think you already mentioned that).

Would it be possible to add a home button next to the ABOUT button which will take you the market page no matter where you are in the app (You can leave home in the draw aswell.)

Is it possible to edit the image in the attached screenshot: 
![image](https://user-images.githubusercontent.com/37632291/80390941-672ddc80-88ad-11ea-9fc2-adcce3bc51ab.png)
If it can be edited please send me the px size and format and we'll get something custom done.

Also would it be possible to increase the width and edit the position of the buttons on the withdraw page. The address box should take up 90% of the card as some addresses can be over 60 characters long.

![image](https://user-images.githubusercontent.com/37632291/80391314-d86d8f80-88ad-11ea-9f24-4f3eadb07733.png)

Otherwise Great job!
Thanks

**Comment by newCodeRunner** [comment]
Application opening small, will maximize on first start, after that take the user's last size - Done

Add Home Button - Done

Custom Installer Image - Done (Provide the image in src/assets/app-installer-sidebar.bmp in the same dimensions and we just need to rebuild then)

Address Box on Wallet page adjusted to take max size available - Done

All the changes can be tested in next release (in order for everything to work correctly - please uninstall the current installed version and directly install the latest version)
