### ISSUE TITLE
MacOS Bug/issues

### ISSUE THREAD

**Issue by fallengravity** [Asymetrex/desktop-app#4]
![Screenshot 2020-05-09 at 12 46 03](https://user-images.githubusercontent.com/37632291/81471817-2494ca00-91f4-11ea-822c-ccb5621af6c8.png)
![Screenshot 2020-05-09 at 12 46 16](https://user-images.githubusercontent.com/37632291/81471823-29f21480-91f4-11ea-81d8-d2fee988c0ff.png)
![Screenshot 2020-05-09 at 12 46 36](https://user-images.githubusercontent.com/37632291/81471825-2b234180-91f4-11ea-9b6d-965a7c4593d5.png)

**Comment by fallengravity** [comment]
![Screenshot 2020-05-09 at 12 55 31](https://user-images.githubusercontent.com/37632291/81471861-750c2780-91f4-11ea-979d-6fab3397970e.png)
![Uploading Screenshot 2020-05-09 at 12.55.40.png…]()

**Comment by fallengravity** [comment]
![Screenshot 2020-05-09 at 16 12 25](https://user-images.githubusercontent.com/37632291/81476035-e6a59f00-920f-11ea-9c93-023279c54939.png)

Also, it is Missing minimize, maximizes and close buttons.

**Comment by newCodeRunner** [comment]
Did you yarn install and yarn rebuild and then yarn dev-electron? or did you just yarn install and then yarn dev-electron directly?

**Comment by fallengravity** [comment]
I used NPM, I will switch to yarn now and test it.

**Comment by fallengravity** [comment]
Switching to yarn is significantly better. Still, there are some warnings/errors:

![Screenshot 2020-05-10 at 12 20 53](https://user-images.githubusercontent.com/37632291/81496574-dc8bab00-92b8-11ea-809f-c71efb35a0c2.png)

![Screenshot 2020-05-10 at 12 21 07](https://user-images.githubusercontent.com/37632291/81496576-e01f3200-92b8-11ea-91f5-6d10d477370b.png)

**Comment by fallengravity** [comment]
When building for production the app gets built fine however doesn't launch it just sits on here:

![Screenshot 2020-05-10 at 12 35 32](https://user-images.githubusercontent.com/37632291/81496844-f3330180-92ba-11ea-995f-713d8dbaba9b.png)

**Comment by newCodeRunner** [comment]
Please confirm if you performed yarn rebuild command?

**Comment by fallengravity** [comment]
My flow:

yarn install && yarn rebuild && yarn build-electron

**Comment by newCodeRunner** [comment]
I had disabled devtools so these couldnt be opened. if you perform the same with latest commit, we should be able to open console.

**Comment by fallengravity** [comment]
Error is attached:

![Screenshot 2020-05-10 at 13 55 19](https://user-images.githubusercontent.com/37632291/81498565-f41d6080-92c5-11ea-97ba-7c18ef84a066.png)

No worries, glad I can be useful lol.

**Comment by newCodeRunner** [comment]
This is an issue related to Quasar framework. Sorry I forgot to mention that. Please follow my temporary hack until my issue with the repo gets solved:

https://github.com/quasarframework/quasar/issues/6893#issuecomment-619676594

You would need to do it every time you add/remove a dep or perform yarn install.

**Comment by fallengravity** [comment]
Indeed commenting out 

```
cfg.build.APP_URL = file://" + __dirname + "/index.html
```

from `node_modules@quasar\app\lib\quasar.conf.js` has fixed the MacOS builds

**Comment by fallengravity** [comment]
![Screenshot 2020-05-10 at 15 27 11](https://user-images.githubusercontent.com/37632291/81500847-19fe3180-92d5-11ea-93c1-21196f10773b.png)

I just noticed MacOS is missing the icon on notifications.

**Comment by fallengravity** [comment]
![Screenshot 2020-05-10 at 15 51 36](https://user-images.githubusercontent.com/37632291/81501010-2767eb80-92d6-11ea-9dfd-e62645055dac.png)

**Comment by newCodeRunner** [comment]
the leak error seems to be with the updater dep, i updated the config for build, please check if it still happens.

looking into the missing icon in notification

**Comment by fallengravity** [comment]
The memory leak is fixed as far as I can tell however building for production is not possible:

![Screenshot 2020-05-11 at 10 19 22](https://user-images.githubusercontent.com/37632291/81539797-04d6e080-9371-11ea-93da-7c83d4dfb01d.png)

**Comment by newCodeRunner** [comment]
Hey, I updated the mac build, can you please test again? Also please check if the content image in notification is replaced? Also which mac version are you using?

**Comment by fallengravity** [comment]
Builds are working again.

Images aren't correct if you can't get it to work, don't worry about it, I'd rather have a console icon than the missing icon from before.

![Screenshot 2020-05-11 at 13 33 38](https://user-images.githubusercontent.com/37632291/81557373-242f3700-938c-11ea-9697-03dc015e30cb.png)

Also noticed this bug when sitting on the Trade Page after a minute or so the Base & Target names change to undefined:

![Screenshot 2020-05-11 at 13 33 09](https://user-images.githubusercontent.com/37632291/81557506-62c4f180-938c-11ea-97b0-969cb15d77f1.png)

**Comment by fallengravity** [comment]
macOS Version: 10.15.4

**Comment by newCodeRunner** [comment]
Since now it is showing the terminal icon, I can get it fixed no problem, found documentation for it. although you would need to help with some more testing, really sorry about that.

And found the undefined bug too, fixed it too.

**Comment by fallengravity** [comment]
Don't rush or stress, I'm happy to test when available. Keep up the solid work 👍

**Comment by newCodeRunner** [comment]
Thanks for your support and understanding, it has been a pleasure working with you so far. did a commit, should both the open points in this issue.

1. Icon
2. Undefined text on Trade Page
