### ISSUE TITLE
Pending Issues with API

### ISSUE THREAD

**Issue by newCodeRunner** [Asymetrex/desktop-app#5]
1. Notifications + Buy/Sell Orders - Pending
2. createOrder api - Pending
3. Withdraw api - Pending

**Comment by newCodeRunner** [comment]
1. Notifications and Order Dialog - Done

For last 2 points, there are few things i needed to clarify since i have limited balance:
1. When i do withdraw, what is the withdraw address? is it the same deposit address of any of the currency?
2. You mentioned earlier, that i can make a trade of 0.000001 3 times with the avail balance, by that you meant the same api .createOrder?

**Comment by fallengravity** [comment]
1.) No, the withdraw address would be provided by the user, its an address on the blockchain, if you tell me which coins you want to test withdrawals on I can provide you with withdraw addresses.

2.) Correct.

**Comment by fallengravity** [comment]
Hey mate, just noticed this, on the trade page each order has its own row would it be possible to have all the orders combined into one row.

![Screenshot 2020-05-13 at 10 00 44](https://user-images.githubusercontent.com/37632291/81787087-d5ef7480-9500-11ea-94a5-ba5ca4b550dc.png)
(XERO/BTC)

What I mean:

![Screenshot 2020-05-13 at 10 03 01](https://user-images.githubusercontent.com/37632291/81787185-f4ee0680-9500-11ea-8011-b29e9b4ba9f7.png)

See how each row is one price but volume & amount are the sum.

**Comment by fallengravity** [comment]
Another thing, please fix balances to and withdrawal amounts to 8 decimal places.

**Comment by newCodeRunner** [comment]
1. Pivot - Done
2. Balance and Locked Fixed to 8 DP - Done
3. Padding Issue in deposit address - Done

4. Withdraw api added - Done, can you please make some tests with your addresses, should work
5. createOrder added - However, i am getting the following error in console every time, am I doing something wrong?

![image](https://user-images.githubusercontent.com/57590297/81810468-6e571a80-953c-11ea-9b55-e702f4dc40cb.png)


```
this.$API.createOrder(market, this.mode, this.amount, this.price, (order) => {
  console.log(order);
  if (isNullOrUndefined(order.result.error) && isNullOrUndefined(order.err)) {
    window.nativeNotify('Asymetrex', this.$t(`msg-${this.mode}-order`, { currency: this.currency }));
    this.dialog = false;
  } else {
    this.$q.notify({ message: this.$t('msg-order-err'), color: 'red', closeBtn: false });
    this.loading = false;
  }
});
```

**Comment by fallengravity** [comment]
Withdraws are giving out 400 errors:

![Screenshot 2020-05-13 at 14 37 49](https://user-images.githubusercontent.com/37632291/81813104-5923c100-9527-11ea-9eb7-74456fc18939.png)

At the top, it shows the correct amount of XERO in the user's account but the other number appears to be the current price (0.00000001) change you please change that to the user's current Base Pair Balance eg: BTC.

![Screenshot 2020-05-13 at 14 36 35](https://user-images.githubusercontent.com/37632291/81813140-680a7380-9527-11ea-9df1-b4d037bd3737.png)

**Comment by fallengravity** [comment]
I will look into order issues now as well as the withdrawal issues.

**Comment by newCodeRunner** [comment]
I am afraid i do not follow you. the following are the same as in withdraw card and deposit card:

![image](https://user-images.githubusercontent.com/57590297/81814865-b4af7800-9542-11ea-9104-5a672265f04c.png)

**Comment by fallengravity** [comment]
Code (I realize now there is a mistake in our documentation stating the number should be negative which is wrong it should be positive):

![Screenshot 2020-05-13 at 15 00 27](https://user-images.githubusercontent.com/37632291/81815710-9a69a000-952a-11ea-995f-67b73cb4e108.png)

Result: 
![Screenshot 2020-05-13 at 15 00 43](https://user-images.githubusercontent.com/37632291/81815721-a190ae00-952a-11ea-94a9-9354358af9d8.png)

**Comment by newCodeRunner** [comment]
i see, so both withdraws and orders are working now?

**Comment by fallengravity** [comment]
Code:

![Screenshot 2020-05-13 at 15 06 32](https://user-images.githubusercontent.com/37632291/81816296-6f338080-952b-11ea-9763-4042b60a238e.png)

Result:
![Screenshot 2020-05-13 at 15 06 44](https://user-images.githubusercontent.com/37632291/81816316-73f83480-952b-11ea-93d1-6277e427f8ff.png)

**Comment by fallengravity** [comment]
They're not working for me, I wrote this code as an example to show you, I will have to go over your code in a few minutes.

**Comment by newCodeRunner** [comment]
hi, I dont see the difference (apart from access codes and tonce which the api is setting) that your code is making and mine

![image](https://user-images.githubusercontent.com/57590297/81818575-a31c9f00-9547-11ea-9989-857f0d760aa9.png)

**Comment by fallengravity** [comment]
```
Problem:
  message body does not match declared format
Resolution:
  when specifying application/json as content-type, you must pass valid application/json in the request's 'body'
```

I've not seen this error before, It looks like it's from the Request library though it looks like the content being sent is being expected to be JSON but isn't.

**Comment by newCodeRunner** [comment]
Could it be due to cross origin?

Please see the comment below:
https://github.com/github/fetch/issues/318#issuecomment-249573195

**Comment by newCodeRunner** [comment]
Hey again, my hunch was correct. You server's mode is probably on 'no-cors' as it should be for security reasons, so it is only expecting result from the same domain i.e. https://asymetrex.com.

But since electron works from file url in production and dev url in development mode, your server was blocking the request due to different origin.

So i tried 2 things:
1. Changed my request content to JSON by changing your API keeping my request origin as is, server accepted, but didnt know what to return since the script at your backend was expecting ''application/x-www-form-urlencoded'' but got JSON. (My proposal is to change your script to accept only JSON and keep the mode at your server as is - so that cross origin JSON requests can work while not compromising your security)

2. Changed my request headers origin and referrer tricking your server into thinking it was from the same domain and it created an order successfully. I am not a backend security expert, in fact have very little experience with backend at all =D, but it looks like a probable security vulnerability - but changing to be able to accept only JSON from both same origin and cross origin might make things more safe - do let me know if i think right

Pushed a commit so you can check it for yourself, please try both createOrder and withdraw

![image](https://user-images.githubusercontent.com/57590297/81892603-eff28b00-95c4-11ea-963c-89565602a9be.png)

**Comment by fallengravity** [comment]
Your fix works for orders & withdrawals. Please leave as is. I'm going to play with the app some more today and see if there are any changes I'd like made, if not, I think we're good to close the order.

**Comment by fallengravity** [comment]
Marking as closed since API is completed.
