### ISSUE TITLE
Errors, Bugs, etc

### ISSUE THREAD

**Issue by fallengravity** [Asymetrex/desktop-app#7]
When placing a buy or sell order the number is calculated to 2e-8 as an example this means the number added to the API request is incorrect - the screenshot below:  

![Screenshot 2020-05-15 at 19 51 56](https://user-images.githubusercontent.com/37632291/82081110-0d6b4600-96e6-11ea-82f2-f05eef8b5b41.png)

When loading a page You get this error in the console:

![Screenshot 2020-05-15 at 19 52 31](https://user-images.githubusercontent.com/37632291/82081270-4efbf100-96e6-11ea-8eae-ab026098ae59.png)

When canceling the order, the order gets successfully canceled however it remains in the table until the page is left and then it's removed, could it refresh the table when an order is canceled video attached:

[Screen Recording 2020-05-15 at 19.54.33.zip](https://github.com/Asymetrex/desktop-app/files/4636213/Screen.Recording.2020-05-15.at.19.54.33.zip)

**Comment by newCodeRunner** [comment]
Hi,

Added a check if the total is too small creating an order (numbers with e-7 or e-8, it wouldnt allow user to create an order) - Done

Loading page Error fixed - Done

Fixed active order not updating, bit of a surprise for me why it didnt - Done (please pause to last second of video, there was only 1 order i could find and not a good video snap =D)

[Cancelled 1.zip](https://github.com/Asymetrex/desktop-app/files/4637952/Cancelled.1.zip)

Noticed your chart API gives the following error sometimes on different currencies:
![image](https://user-images.githubusercontent.com/57590297/82112553-40095300-9767-11ea-9179-e8bec4a60144.png)

Noticed the wallet Info was missing for trade. Added
