### ISSUE TITLE
Buy/Sell Not working

### ISSUE THREAD

**Issue by fallengravity** [Asymetrex/desktop-app#8]
Hey, Buy/Sell still isn't working, there is the same 400 Error as before. I believe the last time they worked was in commit: https://github.com/Asymetrex/desktop-app/commit/48eeb9c577c8eac00f0049c191e848d0cf7926b3

The error in the console is a 400 error not sure what the problem is. I've added enough BTC to your API key so you can try 3 more trades 👍

**Comment by fallengravity** [comment]
Also, don't worry about BITC/BTC market error from chart.asymetrex.com - it gives that error because the chart has no data yet.

**Comment by newCodeRunner** [comment]
Hey again, I made some fixes, was able to create Buy Order but unable to create Sell Order:

Sell Code from your API console.log - Does not work
POST|/api/orders|access_key=yq2VzPW65zumkO8Hdrlpam1klr3EFRyCARDivpCB&market=bitcbtc&price=0.00000001&side=sell&tonce=1589625164593&volume=100

Buy Code from your API console.log - Works
POST|/api/orders|access_key=yq2VzPW65zumkO8Hdrlpam1klr3EFRyCARDivpCB&market=bitcbtc&price=0.00000001&side=buy&tonce=1589625306827&volume=100

**Comment by fallengravity** [comment]
Hey, Sell orders do work, it just so happens that you tried to use Bitc which had 0 balance so there were no coins to sell.

Closing because complete - thanks!
